# Generated by Django 5.2.5 on 2025-08-29 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "contentmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chat.contentmixin",
                    ),
                ),
                ("chat_name", models.CharField(max_length=255, unique=True)),
                (
                    "groupchat_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("private", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_chat_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="chat_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "online_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="online_chat_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("chat.contentmixin",),
        ),
        migrations.CreateModel(
            name="GroupMessages",
            fields=[
                (
                    "contentmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chat.contentmixin",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=("chat.contentmixin",),
        ),
    ]
